version: "3.5"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_USER: wordpress
    ports:
      - 33061:3306
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpressdb